(** File generated by coq-of-ocaml *)
Require Import CoqOfOCaml.CoqOfOCaml.
Require Import CoqOfOCaml.Settings.

Definition sum_digits (digits : int) (base : int) : int :=
  let fix aux (sum : int) (x_value : int) : int :=
    if CoqOfOCaml.Stdlib.le x_value 0 then
      sum
    else
      aux (Z.add sum (Z.modulo x_value base)) (Z.div x_value base) in
  aux 0 digits.
